const  collections = [
    {
        "id": 1,
        "name": "Indomptables de Cartier",
        "image": "https://www.cartier.com/on/demandware.static/-/Sites-cartier-storefront-US/default/dwf7ed7242/MegaMenu/HJ_2022/07_PIECES%20DISPO%20EN%20LIGNE/HAUTE-JO_VIGNETTES_400x400_CAR_CRH6038815.png",
        "description": "A collection that challenges the Cartier menagerie and pushes the imposed boundaries of figuration. We would be happy to welcome you in a selection of boutiques to advise you and answer your questions about our High Jewelry creations.",
        "status": "best-seller", // ["featured", "limited-edition", "best-seller", "luxury", "trending", "popular" ],
        "banner": "https://www.cartier.com/on/demandware.static/-/Library-Sites-CartierSharedLibrary-BGTJ/default/dw5f25a289/plp/High%20Jewellery/all-creations/Indomptables/Header/01_LES%20INDOMPTABLES%20PLP%20SFCC%20_%20NEL%20_%20MAN%201920x800.jpg",
    },
    {
        "id": 2,
        "name": "Panthère de Cartier",
        "image": "https://www.cartier.com/on/demandware.static/-/Sites-cartier-storefront-US/default/dwf2fcaeb8/MegaMenu/April_update/MEGAMENU_JEWELLERY_ALL-COLLECTION_PANTHERE.png",
        "description": "From necklaces to bracelets and rings, the panther likes powerful volumes, pure lines, and essential design.",
        "status": "featured", // ["featured", "limited-edition", "best-seller", "luxury", "trending", "popular" ],
        "banner": "https://www.cartier.com/on/demandware.static/-/Library-Sites-CartierSharedLibrary-BGTJ/default/dw58a4af63/plp-banners/DESKTOP%20PLP%20HEADER_Panthere-Jewelry.jpg",
    },
    {
        "id": 3,
        "name": "Flora & Fauna",
        "image": "https://www.cartier.com/on/demandware.static/-/Sites-cartier-storefront-US/default/dw556f225f/MegaMenu/HJ_2022/07_PIECES%20DISPO%20EN%20LIGNE/Faune%20et%20Flore.png",
        "description": "There is nothing romantic or sweet when it comes to nature at Cartier, instead it is a unique and liberated vision of flora and fauna. We would be happy to welcome you in a selection of boutiques to advise you and answer your questions about our High Jewelry creations.",
        "status": "featured", // ["featured", "limited-edition", "best-seller", "luxury", "trending", "popular" ],
        "banner": "https://www.cartier.com/on/demandware.static/-/Library-Sites-CartierSharedLibrary-BGTJ/default/dw2f38d1f2/HEADERS-1920px-par-800px-HJ-NEW-FAUNE-ET-FLORE-V2-5262022.jpg",
    },
    {
        "id": 4,
        "name": "Indomptables de Cartier",
        "image": "https://www.cartier.com/on/demandware.static/-/Sites-cartier-storefront-US/default/dwf7ed7242/MegaMenu/HJ_2022/07_PIECES%20DISPO%20EN%20LIGNE/HAUTE-JO_VIGNETTES_400x400_CAR_CRH6038815.png",
        "description": "A collection that challenges the Cartier menagerie and pushes the imposed boundaries of figuration. We would be happy to welcome you in a selection of boutiques to advise you and answer your questions about our High Jewelry creations.",
        "status": "limited-edition", // ["featured", "limited-edition", "best-seller", "luxury", "trending", "popular" ],
        "banner": "https://www.cartier.com/on/demandware.static/-/Library-Sites-CartierSharedLibrary-BGTJ/default/dw5f25a289/plp/High%20Jewellery/all-creations/Indomptables/Header/01_LES%20INDOMPTABLES%20PLP%20SFCC%20_%20NEL%20_%20MAN%201920x800.jpg",
    },
    {
        "id": 5,
        "name": "Panther",
        "image": "https://www.cartier.com/on/demandware.static/-/Sites-cartier-storefront-US/default/dw91fc3c8d/MegaMenu/HJ_2022/07_PIECES%20DISPO%20EN%20LIGNE/La%20panthere%20animal%20emblematique.png",
        "description": "A wild animal whose symbolism and elegance have reigned over the Maison's creativity since its first appearance in 1914. We would be happy to welcome you in a selection of boutiques to advise you and answer your questions about our High Jewelry creations.",
        "status": "featured", // ["featured", "limited-edition", "best-seller", "luxury", "trending", "popular" ],
        "banner": "https://www.cartier.com/on/demandware.static/-/Library-Sites-CartierSharedLibrary-BGTJ/default/dw4ef236aa/HEADERS-1920px-par-800px-HJ-NEW-ICONIC%20PANTHER-1-5262022.jpg",
    },
    {
        "id": 6,
        "name": "Architecture & Purity",
        "image": "https://www.cartier.com/on/demandware.static/-/Sites-cartier-storefront-US/default/dwcdf1b59c/MegaMenu/HJ_2022/07_PIECES%20DISPO%20EN%20LIGNE/Architecture%20de%20lumi%C3%A8re.png",
        "description": "To liberate a gemstone’s radiance, Cartier envisions its creations as architectural pieces of light. We would be happy to welcome you in a selection of boutiques to advise you and answer your questions about our High Jewelry creations.",
        "status": "featured", // ["featured", "limited-edition", "best-seller", "luxury", "trending", "popular" ],
        "banner": "https://www.cartier.com/on/demandware.static/-/Library-Sites-CartierSharedLibrary-BGTJ/default/dw4191ca73/HEADERS-1920px-par-800px-HJ-NEW-ARCH%20OF%20LIGHT-1-5262022.jpg",
    },
    {
        "id": 7,
        "name": "Geometry & Contrasts",
        "image": "https://www.cartier.com/on/demandware.static/-/Sites-cartier-storefront-US/default/dwebe803d1/MegaMenu/HJ_2022/07_PIECES%20DISPO%20EN%20LIGNE/Geometrie%20et%20contrastes.png",
        "description": "Two powerful markers of the Cartier style that combine architectural design and symmetry with the power of intense chromatic contrasts. We would be happy to welcome you in a selection of boutiques to advise you and answer your questions about our High Jewelry creations.",
        "status": "luxury", // ["featured", "limited-edition", "best-seller", "luxury", "trending", "popular" ],
        "banner": "https://www.cartier.com/on/demandware.static/-/Library-Sites-CartierSharedLibrary-BGTJ/default/dw20831954/HEADERS-1920px-par-800px-HJ-NEW-GEOMETRY%20&%20CONTRASTS-1-5262022.jpg",
    },
    {
        "id": 8,
        "name": "Fine Jewelry Watches",
        "image": "https://www.cartier.com/on/demandware.static/-/Sites-cartier-storefront-US/default/dw29fdf2ac/MegaMenu/HJ_2022/07_PIECES%20DISPO%20EN%20LIGNE/Montres%20precieuses.png",
        "description": "Linking the two founding crafts of the Maison, jewelry and watchmaking, these pieces incorporate constantly renewed creativity.",
        "status": "featured", // ["featured", "limited-edition", "best-seller", "luxury", "trending", "popular" ],
        "banner": "https://www.cartier.com/on/demandware.static/-/Library-Sites-CartierSharedLibrary-BGTJ/default/dwa37c60aa/HAUTE-JO_1920x800_PLP_JWL-WATCHES-5262022.png",
    },
    {
        "id": 9,
        "name": "Diamond Collections",
        "image": "https://www.cartier.com/on/demandware.static/-/Sites-cartier-storefront-US/default/dwb09743c3/MegaMenu/jewellery/collection/diamond-collection/VIGNETTE_400x400_DIAMONDS_COLLECTIONS.jpg",
        "description": "At Cartier, love is celebrated with diamonds. The Maison's signature is born of the meeting between exceptional savoir-faire and a creative vision. Each creation exudes precious personality and each diamond radiates a singular brilliance.",
        "status": "featured", // ["featured", "limited-edition", "best-seller", "luxury", "trending", "popular" ],
        "banner": "https://www.cartier.com/on/demandware.static/-/Library-Sites-CartierSharedLibrary-BGTJ/default/dwb69dec62/plp/jewellery/collections/diamond-collection/header/1920x800.jpg",
    },
    {
        "id": 10,
        "name": "C De Cartier",
        "image": "https://www.cartier.com/on/demandware.static/-/Sites-cartier-storefront-US/default/dw75969756/MegaMenu/jewellery/collection/ALL%20C.jpg",
        "description": "Graphic and refined, Cartier's initial inspires a collection of pendants and earrings that enhance diamonds.",
        "status": "limited-edition", // ["featured", "limited-edition", "best-seller", "luxury", "trending", "popular" ],
        "banner": "https://www.cartier.com/on/demandware.static/-/Library-Sites-CartierSharedLibrary-BGTJ/default/dw8fff744e/plp/jewellery/collections/c-de-cartier/header/Header_1920x800.jpg",
    },

]
export default collections;